### ISSUE TITLE
How can I use this library if I already have one modole registered？

### ISSUE THREAD

**Issue by pangpangshui** [188080501/JQQRCode#1]
My registered module like this:
`QQmlApplicationEngine engine;
engine.rootContext()->setContextProperty("device", &d);
QPM_INIT(engine)
engine.load(QUrl(QStringLiteral("qrc:/assets/main.qml")));`

and I have browse your code, I found that if I want to use your QR code library, I must import it by using this code:
`JQQRCODEREADERFORQML_REGISTERTYPE( engine );`
which is been define in file "JQQRCodeReaderForQml.h",the code is:
`#   define JQQRCODEREADERFORQML_REGISTERTYPE( engine ) \
    engine.rootContext()->setContextProperty( "JQQRCodeReaderForQmlManage", new JQQRCodeReaderForQmlManage ); \
    engine.addImportPath( ":/JQQRCodeReader/" );
#endif`

this is similar with what I define my module, so how can I do to use your library? thank you

**Comment by 188080501** [comment]
```setContextProperty```
Can be used many times

**Comment by pangpangshui** [comment]
@188080501 
I tried to add this code in my main.cpp:
```c++
JQQRCODEREADERFORQML_REGISTERTYPE( engine );
```
And then I builded it, but it has an error:
`error: undefined reference to 'JQQRCodeReaderForQmlManage::JQQRCodeReaderForQmlManage()`
It seems that this project can't find file `JQQRCodeReaderForQml.cpp` beacause the constructor function of `JQQRCodeReaderForQmlManage()` is define in `JQQRCodeReaderForQml.cpp`, so how can I fix it? Modify the `JQLibrary.pri` file to find the cpp file or is there any other ways?

**Comment by 188080501** [comment]
Add 
```
include( $$PWD/../../sharedlibrary/JQLibrary/JQLibrary.pri )
include( $$PWD/../../sharedlibrary/JQLibrary/JQQRCodeReader.pri )
```
in your pro file.

**Comment by 188080501** [comment]
And..... do not forget add
```
QT *= core qml quick concurrent multimedia
```
in your pro file

**Comment by pangpangshui** [comment]
Thanks, I fogot to add 
```c++
QT += concurrent multimedia
```

Once I added this line, it worked.

And then I  transplant my project on my Android phone, then I found that I can't get the permission of camera, so I add this permission in the file `AndroidManifest.xml`, it works again. So execited. But once my app call the camara, the app crashed and died. I'm crazy.  

Receive the following error message:
```java
E/art     (15630): No implementation found for void org.qtproject.qt5.android.multimedia.QtSurfaceTextureListener.notifyFrameAvailable(long) (tried Java_org_qtproject_qt5_android_multimedia_QtSurfaceTextureListener_notifyFrameAvailable and Java_org_qtproject_qt5_android_multimedia_QtSurfaceTextureListener_notifyFrameAvailable__J)
D/AndroidRuntime(15630): Shutting down VM
E/AndroidRuntime(15630): FATAL EXCEPTION: main
E/AndroidRuntime(15630): Process: org.qtproject.example.mobilePatientrounds3, PID: 15630
E/AndroidRuntime(15630): java.lang.UnsatisfiedLinkError: No implementation found for void org.qtproject.qt5.android.multimedia.QtSurfaceTextureListener.notifyFrameAvailable(long) (tried Java_org_qtproject_qt5_android_multimedia_QtSurfaceTextureListener_notifyFrameAvailable and Java_org_qtproject_qt5_android_multimedia_QtSurfaceTextureListener_notifyFrameAvailable__J)
E/AndroidRuntime(15630): 	at org.qtproject.qt5.android.multimedia.QtSurfaceTextureListener.notifyFrameAvailable(Native Method)
E/AndroidRuntime(15630): 	at org.qtproject.qt5.android.multimedia.QtSurfaceTextureListener.onFrameAvailable(QtSurfaceTextureListener.java:56)
E/AndroidRuntime(15630): 	at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:203)
E/AndroidRuntime(15630): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(15630): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(15630): 	at android.app.ActivityThread.main(ActivityThread.java:5290)
E/AndroidRuntime(15630): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15630): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(15630): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
E/AndroidRuntime(15630): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
I/WtEventController( 4346): Receive am_crash event for pid: 15630
I/Process (15630): Sending signal. PID: 15630 SIG: 9
I/ActivityManager(  830): Process org.qtproject.example.mobilePatientrounds3 (pid 15630) has died
D/ActivityManager(  830): cleanUpApplicationRecord -- 15630
W/InputMethodManagerService(  830): Got RemoteException sending setActive(false) notification to pid 15630 uid 10191
```

**_Is there something I fogot to set aiming at the Android system? look forward to your reply_**
Qt version: 5.8 for Android;    test Android system : Android 5.1.1 and Adnroid 6.0
@188080501

**Comment by 188080501** [comment]
I have not seen this problem
What is your Qt version?
What is your Android device system version?

**Comment by pangpangshui** [comment]
My Qt version: 5.8 for Android; test Android device system : Android 5.1.1 and Android 6.0.
Strangely, your demo runs well in my android system(Android 5.1.1). My project is an app about bluetooth, witch is used qml and c++, is there any problem in my Project?

And my jdk version is 1.8.0_45_x64, 
ndk version is android-ndk-r12b, 
sdk api version is android 23,
ant version is apache-ant-1.9.9


Is that possible for me to requesting permissions at run time rather than define it in the file `AndroidManifest.xml`

**Comment by 188080501** [comment]
If run my demo (QRCodeReaderForQml), is normal, The scan function is used normally.
But if into your project, it can not be used normally?

**Comment by pangpangshui** [comment]
Exactly yes, once I call the camera, the app will be crashed and died. I had never seen the image through a camera when I click the button which would call the camera. That is to say, I can't call the camera in my project.

Or is there the reason like this: [https://github.com/nspire-emus/firebird/issues/89](url)
Should I need to set the target SDK lower than 23?

**Comment by pangpangshui** [comment]
After some debug, I found my app died in this function located in file `JQQRCodeReader.cpp`
```c++

1. QString JQQRCodeReader::decodeImage(const QImage &image, const int &decodeType)
2. {
3.     semaphore_->acquire( 1 );
4. 
5.     zxing::Ref< zxing::Result > res;
6.     QMetaObject::invokeMethod( this, "decodingStarted", Qt::QueuedConnection );
7. 
8.     if( image.isNull() )
9.     {
10.         qDebug() << "JQQRCodeReader::decodeImage: error: image is null";
11.         emit decodingFinished( false );
12. 
13.         semaphore_->release( 1 );
14.         return { };
15.     }
16. 
17.     auto ciw = new ImageWrapper( image );
18. 
19.     zxing::Ref< zxing::LuminanceSource > imageRef( ciw );
20.     zxing::GlobalHistogramBinarizer* binz = new zxing::GlobalHistogramBinarizer( imageRef );
21. 
22.     zxing::Ref< zxing::Binarizer > bz( binz );
23.     zxing::BinaryBitmap *bb = new zxing::BinaryBitmap( bz );
24. 
25.     zxing::Ref< zxing::BinaryBitmap > ref( bb );
26. 
27.     try
28.     {
29.         res = decoder_->decode( ref, static_cast< zxing::DecodeHints >( static_cast< unsigned int >( decodeType ) ) );
30.         QString string = QString( res->getText()->getText().c_str() );
31.         QMetaObject::invokeMethod( this, "tagFound", Qt::QueuedConnection, Q_ARG( QString, string ) );
32.         QMetaObject::invokeMethod( this, "decodingFinished", Qt::QueuedConnection, Q_ARG( bool, true ) );\
33. 
34.         semaphore_->release( 1 );
35.         return string;
36.     }
37.     catch ( zxing::Exception & )
38.     {
39.         QMetaObject::invokeMethod( this, "decodingFinished", Qt::QueuedConnection, Q_ARG( bool, false ) );
40. 
41.         semaphore_->release( 1 );
42.     }
43. 
44.     return { };
45. }

```

When app run into the line 29, it would throw the exception and jump to line 37-42. These would continue two times, and then the app died. But I don't know what happened because I know nothing about the qzxing lib. Some help please?

**Comment by pangpangshui** [comment]
I found the reason why the app  died when I call the camera.
  The file `AndroidManifest.xml` has not configured correctly.
  In the permission area, I fix permission define like this:
```xml

1. <!-- The following comment will be replaced upon deployment with default permissions based on the dependencies of the application.
2.          Remove the comment if you do not require these default permissions. -->
3.         <uses-permission android:name="android.permission.INTERNET"/>
4.     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
5.     <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
6.     <uses-permission android:name="android.permission.BLUETOOTH"/>
7.     <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
8.     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
9.     <uses-permission android:name="android.permission.RECORD_AUDIO"/>
10. 
11. 
12.     <!-- The following comment will be replaced upon deployment with default features based on the dependencies of the application.
13.          Remove the comment if you do not require these default features. -->
14.          <uses-feature android:name="android.hardware.camera" android:required="false"/>
15.      <uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>
16.      <uses-feature android:name="android.hardware.microphone" android:required="false"/>
17.      <uses-feature android:glEsVersion="0x00020000" android:required="true"/>
18. 
19. <uses-permission android:name="android.permission.CAMERA"/>

```
  I add the line 4, 9, 14, 15, 16.

  And in the dependence area, I modified it like this:
```xml
<!-- Run with local libs -->
<meta-data android:name="android.app.load_local_jars" android:value="jar/QtAndroid.jar:jar/QtAndroid-bundled.jar:jar/QtAndroidBearer.jar:jar/QtAndroidBearer-bundled.jar:jar/QtAndroidBluetooth.jar:jar/QtAndroidBluetooth-bundled.jar:jar/QtMultimedia.jar:jar/QtMultimedia-bundled.jar"/>
<meta-data android:name="android.app.static_init_classes" android:value="org.qtproject.qt5.android.bluetooth.QtBluetoothBroadcastReceiver:org.qtproject.qt5.android.bluetooth.QtBluetoothBroadcastReceiver:org.qtproject.qt5.android.multimedia.QtMultimediaUtils:org.qtproject.qt5.android.multimedia.QtMultimediaUtils"/>
```

  I add `:jar/QtMultimedia.jar:jar/QtMultimedia-bundled.jar` in `android.app.load_local_jars`
and add `:org.qtproject.qt5.android.multimedia.QtMultimediaUtils:org.qtproject.qt5.android.multimedia.QtMultimediaUtils` in `android.app.static_init_classes`

  After I did this, my app can work well when it call the camera.
  Thanks for your demo.
^_^

**Comment by 188080501** [comment]
I'm glad you solved the problem.

And, When i develop the Android program, I have not configured these parameters, program is normal,  I do not know what's the difference, maybe is version?

**Comment by pangpangshui** [comment]
I don't know. I think Maybe It's a bug with Qt. Thanks for your help.
